name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npx awesome-lint
